spring:
  data:
    redis:
      host: community-redis
      port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://community-mysql:3306/wanted?createDatabaseIfNotExist=true&serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

token:
  access-expired-time: 300000
  refresh-expired-time: 7000000
  secret: token_key
